### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yograterol**
Ideas for the roadmap

### CODE REVIEW

**Comment by diegoug** [comment]
* asociar el cargo de stripe a la metadata
* el end point de usuario para pedir generar el cargo a la app

**Comment by yograterol** [comment]
@diegoug yep, the second point is here https://github.com/PlatziDev/ribboard/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R10

About the firts point, is here too https://github.com/PlatziDev/ribboard/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R8, but that data did not save into of `metadata` field, that data will be the root data in the document.

**Comment by yograterol** [comment]
Make endpoints for settings the app is a must point.

The initial settings can be:
- CRUD apps. (Here the app will can be assign to an key of stripe) ex: An app for dev and another for production.
- Add/Update stripe key to the services.

**Comment by yograterol** [comment]
Any comments? If not I will merge the PR.

**Comment by yograterol** [comment]
We merge that.

**Pull request merged**
